# Generated by Django 3.2.9 on 2022-05-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220408_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='profession',
            new_name='profession_id',
        ),
        migrations.RenameField(
            model_name='medicalcard',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='card',
            new_name='card_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='doctor',
            new_name='doctor_id',
        ),
    ]
