# Generated by Django 3.2.9 on 2022-05-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220501_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='room',
            field=models.IntegerField(verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='app_date',
            field=models.DateTimeField(max_length=255, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='diagnosis',
            field=models.CharField(max_length=255, verbose_name='diagnosis'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth',
            field=models.DateField(max_length=255, verbose_name='bithday'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport',
            field=models.CharField(max_length=255, verbose_name='passport'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=255, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='end_date',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_date',
            field=models.DateTimeField(max_length=255, verbose_name='start date'),
        ),
    ]
