# Generated by Django 3.2.9 on 2022-05-01 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220501_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='card_id',
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='patient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
            preserve_default=False,
        ),
    ]
