# Generated by Django 3.2.9 on 2022-05-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220501_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalcard',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
