# Generated by Django 3.2.9 on 2022-05-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220502_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='surname',
            field=models.CharField(default=1, max_length=255, verbose_name='surname'),
            preserve_default=False,
        ),
    ]
