# Generated by Django 3.2.9 on 2022-05-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220503_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth',
            field=models.DateField(blank=True, max_length=255, verbose_name='bithday'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='passport'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(blank=True, max_length=255, verbose_name='surname'),
        ),
    ]
