# Generated by Django 3.2.9 on 2022-05-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220504_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='bithday'),
        ),
    ]
